spring:
  application:
    name: core
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]

oauth:
  google:
    client-id: ${OAUTH_GOOGLE_CLIENT_ID}
    client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
    redirect-uri: ${OAUTH_GOOGLE_REDIRECT_URI}

  kakao:
    client-id: ${OAUTH_KAKAO_CLIENT_ID}
    client-secret: ${OAUTH_KAKAO_CLIENT_SECRET}
    redirect-uri: ${OAUTH_KAKAO_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-ms: ${JWT_ACCESS_TOKEN_EXPIRE_MS}
  refresh-token-expire-ms: ${JWT_REFRESH_TOKEN_EXPIRE_MS}

cits:
  api-url: ${CITS_API_URL}
  api-key: ${CITS_API_KEY}

valhalla:
  url: ${VALHALLA_URL}

bus-stop:
  api-url: https://apis.data.go.kr/1613000/BusSttnInfoInqireService/getSttnNoList
  api-key: ${BUS_STOP_API_KEY}
  city-codes: ${BUS_STOP_CITY_CODES:11,25,26,27,28,29,30,36,41,42,43,44,45,46,47,48,50}
  page-size: 1000

spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: pacer-backend